
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  
  migrate:
    build: .
    command: goose up
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db
  
  app:
    build: .
    environment:
      - DBSTRING=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - migrate
      - db
    command: ./main
  
volumes:
  db_data: