
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_data_prod:/var/lib/postgresql/data
    networks:
      - prod_network
  
  migrate:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest
    command: goose up
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
    depends_on:
      - db
    
    networks:
      - prod_network
  
  app:
    image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:latest
    environment:
      - DBSTRING=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - migrate
      - db
    restart: always

    networks:
      - prod_network
  
volumes:
  db_data_prod:

networks:
  prod_network:
    driver: bridge