// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Shorturl struct {
	Sid         int32
	ShortCode   string
	OriginalUrl string
	CreatedAt   pgtype.Timestamp
}
