// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: shorturls.sql

package db

import (
	"context"
)

const fineOne = `-- name: FineOne :one
SELECT sid, short_code, original_url, created_at FROM shorturls
WHERE short_code = $1
`

func (q *Queries) FineOne(ctx context.Context, shortCode string) (Shorturl, error) {
	row := q.db.QueryRow(ctx, fineOne, shortCode)
	var i Shorturl
	err := row.Scan(
		&i.Sid,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}

const insertSurl = `-- name: InsertSurl :one
INSERT INTO shorturls (short_code , original_url)
VALUES ($1 , $2)
RETURNING sid, short_code, original_url, created_at
`

type InsertSurlParams struct {
	ShortCode   string
	OriginalUrl string
}

func (q *Queries) InsertSurl(ctx context.Context, arg InsertSurlParams) (Shorturl, error) {
	row := q.db.QueryRow(ctx, insertSurl, arg.ShortCode, arg.OriginalUrl)
	var i Shorturl
	err := row.Scan(
		&i.Sid,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
	)
	return i, err
}
